// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { General } from "./General";
import type { Overview } from "./Overview";

export type Options = { general: General, overview: Overview, };
