// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportTypes } from "./ExportTypes";

export type Overview = { name: string, tags: string, selected_export_type: ExportTypes | null, playtime: number, };
