// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewFields } from "./options/overview/OverviewFields";
import type { SettingsFields } from "./options/settings/SettingsFields";

export type InstanceFields = { "Overview": OverviewFields } | { "Settings": SettingsFields };
