// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationFinish } from "./OperationFinish";
import type { OperationStart } from "./OperationStart";
import type { OperationUpdate } from "./OperationUpdate";

export type OperationEvent = { "start": OperationStart } | { "update": OperationUpdate } | { "finish": OperationFinish };
