// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseMessage } from "./BaseMessage";
import type { OperationEvent } from "./OperationEvent";

export type OperationMessage = { base: BaseMessage, data: OperationEvent, };
