// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseMessage } from "./BaseMessage";
import type { ScanData } from "./ScanData";

export type ScanMessage = { base: BaseMessage, data: ScanData, };
