// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanInfo } from "./ScanInfo";
import type { ScanIntegrity } from "./ScanIntegrity";

export type ScanData = { integrity: ScanIntegrity, info: ScanInfo | null, };
