// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirStatus } from "./DirStatus";
import type { FileStatus } from "./FileStatus";

export type TargetStatus = { "file": FileStatus } | { "dir": DirStatus };
