// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportTypes } from "./ExportTypes";

export type OverviewFields = { name: string | null, tags: string | null, export_type: ExportTypes | null, playtime: bigint | null, };
