// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BaseMessage = { 
/**
 * Unique ID of message
 */
message_id: string, 
/**
 * ID of long-running operation
 */
operation_id: string | null, 
/**
 * ID of source request from client
 */
request_id: string | null, 
/**
 * Time mark in RFC3339
 */
timestamp: string, 
/**
 * ID of related operation (for chains)
 */
correlation_id: string | null, };
