// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStage } from "./OperationStage";

export type OperationStart = { stages: Array<OperationStage>, };
