// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStage } from "./OperationStage";
import type { ProcessStatus } from "./ProcessStatus";
import type { ProcessTarget } from "./ProcessTarget";
import type { StageResult } from "./StageResult";

export type OperationUpdate = { "type": "SingleDeterminable", "details": { stage: OperationStage, status: ProcessStatus, target: ProcessTarget | null, } } | { "type": "Determinable", "details": { stage: OperationStage, status: ProcessStatus, target: ProcessTarget | null, current: number, total: number, } } | { "type": "Indeterminable", "details": { stage: OperationStage, status: ProcessStatus, } } | { "type": "Completed", "details": StageResult };
