// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationStage = "fetch_manifest" | "download_libs" | "download_assets" | "verify_files" | "create_structure" | "scan_instances";
