// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressUnit } from "./ProgressUnit";
import type { ScanInfo } from "./ScanInfo";
import type { ScanIntegrity } from "./ScanIntegrity";
import type { TargetStatus } from "./TargetStatus";

export type ProcessTarget = { "type": "File", status: TargetStatus, name: string, unit: ProgressUnit | null, current: number | null, size: number | null, } | { "type": "Dir", } | { "type": "Instance", integrity: ScanIntegrity, info: ScanInfo | null, };
