// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestedTask = { "init_instance": { instance_id: string, config: string, } } | { "run_instance": { instance_id: string, parameters: Array<string>, } } | { "scan_for_instances": { scan_range: [number, number], } };
