// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanIntegrity = { manifest_path: string, manifest_exist: boolean, instance_path: string, instance_exist: boolean, };
