// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStage } from "./OperationStage";
import type { StageError } from "./StageError";
import type { StageStatus } from "./StageStatus";

export type StageResult = { status: StageStatus, stage: OperationStage, duration_secs: number, error: StageError | null, };
