// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStage } from "./OperationStage";
import type { TaskProgress } from "./TaskProgress";
import type { TaskStatus } from "./TaskStatus";

export type Task = { name: string, status: TaskStatus, stage: OperationStage | null, progress: TaskProgress, message: string | null, };
