// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationMessage } from "./OperationMessage";
import type { ScanMessage } from "./ScanMessage";

export type WsMessage = { "type": "operation", "payload": OperationMessage } | { "type": "scan", "payload": ScanMessage } | { "type": "task" };
